### ISSUE TITLE
Better contribution guidelines. 

### ISSUE THREAD

**Issue by honestly-nuts** [stringtherapy/hemi#2]
Hello, I came here from the reddit post. And I noticed that you don't have contributing guidelines. And as a open source project, 
that is pretty important. I also think you need to mention which files are doing what so people new don't have to search through the
code to understand.

**Comment by stringtherapy** [comment]
Thanks! I will update those.

**Comment by honestly-nuts** [comment]
It is fixed but I do recommend linking it in the readme by saying something like ` # Contributing\n contribution guidlines are given [here](link to contributing.md)`

**Comment by stringtherapy** [comment]
Good suggestion! Done
